version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=example
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - 5000:5000

  redis:
    image: redis:latest

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: my_db
