version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
    depends_on:
      - db
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    container_name: frontend

  redis:
    image: redis:latest

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: my_db
    volumes:
      - ./database:/var/lib/postgresql/data
