version: '3.8'

services:
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
    - 3000:3000

  backend:
    build: ./ml-kurkkumopo-backend
    ports:
    - 5000:5000
    links:
      - training
    volumes:
      - tr:/src/model
    depends_on:
      - training

  training:
    build: ./ml-kurkkumopo-training
    volumes:
      - tr:/src/model
      - tr:/src/imgs
      - tr:/src/data
volumes:
  tr: